# Generated by Django 5.2.12 on 2026-03-18 11:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('source_url', models.URLField(unique=True, verbose_name='Ссылка на источник')),
                ('date_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата мероприятия')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание (qwen-markdown)')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст (HTML)')),
                ('content_plain', models.TextField(blank=True, verbose_name='Текст (plain)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Спарсенное мероприятие',
                'verbose_name_plural': 'Спарсенные мероприятия',
                'ordering': ['-date_at', '-created_at'],
            },
        ),
    ]
