# Generated by Django 5.2.8 on 2026-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedevent',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
    ]
