# Generated by Django 5.2.8 on 2026-03-24 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_parser', '0002_parsedevent_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='parsed_event_joined', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
