# Generated by Django 5.2.8 on 2025-12-04 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplatform', '0002_alter_user_role_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сообщества')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('location', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('max_participants', models.PositiveIntegerField(verbose_name='Максимальное количество участников')),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/events', verbose_name='Фото мероприятий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizator', models.ForeignKey(limit_choices_to={'role': 'ORGANIZER'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
        ),
    ]
