# Generated by Django 5.2.8 on 2025-12-07 17:18

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplatform', '0005_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myplatform.faculty'),
        ),
    ]
