# Generated by Django 5.2.8 on 2026-02-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplatform', '0006_user_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя'),
        ),
    ]
