# Generated by Django 5.2.8 on 2026-02-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplatform', '0007_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_text',
            field=models.TextField(blank=True, default='', verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
    ]
