# Generated by Django 5.2.8 on 2026-02-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplatform', '0009_rename_middle_name_user_middle_name_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД', null=True, verbose_name='Дата рождения'),
        ),
    ]
