# Generated by Django 5.2.8 on 2026-03-08 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplatform', '0010_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_joined', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
