# Generated by Django 5.2.8 on 2026-03-10 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplatform', '0011_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='communities_joined', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
