# Generated by Django 5.2.8 on 2026-04-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplatform', '0012_community_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальное количество участников'),
        ),
    ]
