# Generated by Django 5.2.8 on 2026-04-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplatform', '0013_community_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество баллов'),
        ),
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество баллов'),
        ),
    ]
